# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Wesley Hsieh
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/resume-2021" # the subpath of the site
url: "https://wesley-hsieh.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: hsieh.wesley@gmail.com
      link: mailto:hsieh.wesley@gmail.com
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/wesley-hsieh-3155ab19a/
    - name: GitHub
      link: https://github.com/wesley-hsieh
      
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
